[2021-11-11 17:34:27,980][engineer_data_logger][INFO] - Load data into spark
[2021-11-11 17:34:32,001][engineer_data_logger][INFO] - Do some simple transformations
[2021-11-11 17:34:32,093][engineer_data_logger][INFO] - Find close weather stations to ride stations
[2021-11-11 17:34:32,094][merge_stations_logger][INFO] - Load into pandas
[2021-11-11 17:34:52,616][merge_stations_logger][INFO] - Process 556335 ride stations and 917 weather stations
[2021-11-11 17:34:53,217][merge_stations_logger][INFO] - Building KD-Tree
[2021-11-11 17:34:53,218][merge_stations_logger][INFO] - Query points
[2021-11-11 17:34:56,530][py4j.clientserver][INFO] - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\SuperTom\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
[2021-11-11 17:34:56,535][py4j.clientserver][INFO] - Closing down clientserver connection
[2021-11-11 17:34:56,535][root][ERROR] - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\SuperTom\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
